import next from "@howells/lint/oxlint/next";
import { disabledReactDoctorRules } from "@howells/lint/oxlint/react-doctor-rules";

const legacyCompatibilityRules = {
  complexity: "off",
  "default-case": "off",
  "func-style": "off",
  "howells/no-runtime-dynamic-imports": "off",
  "import/consistent-type-specifier-style": "off",
  "jsx-a11y/control-has-associated-label": "off",
  "max-lines": "off",
  "max-lines-per-function": "off",
  "max-statements": "off",
  "no-inline-comments": "off",
  "no-negated-condition": "off",
  "no-nested-ternary": "off",
  "no-plusplus": "off",
  "no-restricted-properties": "off",
  "no-shadow": "off",
  "no-unused-vars": "off",
  "no-use-before-define": "off",
  "prefer-destructuring": "off",
  "prefer-named-capture-group": "off",
  "promise/prefer-await-to-callbacks": "off",
  "promise/prefer-await-to-then": "off",
  "react/no-object-type-as-default-prop": "off",
  "react/no-unstable-nested-components": "off",
  "require-await": "off",
  "require-unicode-regexp": "off",
  "sort-keys": "off",
  "typescript/consistent-return": "off",
  "typescript/method-signature-style": "off",
  "typescript/no-base-to-string": "off",
  "typescript/no-deprecated": "off",
  "typescript/no-dynamic-delete": "off",
  "typescript/no-floating-promises": "off",
  "typescript/no-misused-promises": "off",
  "typescript/no-redundant-type-constituents": "off",
  "typescript/no-unnecessary-type-conversion": "off",
  "typescript/no-unnecessary-type-assertion": "off",
  "typescript/no-unnecessary-type-parameters": "off",
  "typescript/no-unsafe-argument": "off",
  "typescript/no-unsafe-assignment": "off",
  "typescript/no-unsafe-call": "off",
  "typescript/no-unsafe-member-access": "off",
  "typescript/no-unsafe-return": "off",
  "typescript/no-unsafe-type-assertion": "off",
  "typescript/prefer-nullish-coalescing": "off",
  "typescript/require-array-sort-compare": "off",
  "typescript/restrict-template-expressions": "off",
  "typescript/return-await": "off",
  "typescript/strict-boolean-expressions": "off",
  "typescript/strict-void-return": "off",
  "typescript/switch-exhaustiveness-check": "off",
  "typescript/use-unknown-in-catch-callback-variable": "off",
  "unicorn/consistent-function-scoping": "off",
  "unicorn/import-style": "off",
  "unicorn/no-array-sort": "off",
  "unicorn/no-lonely-if": "off",
  "unicorn/no-negated-condition": "off",
  "unicorn/no-nested-ternary": "off",
};

export default {
  extends: [next],
  ignorePatterns: ["dist/**", "node_modules/**"],
  rules: {
    ...disabledReactDoctorRules,
    ...legacyCompatibilityRules,
  },
  overrides: [
    {
      files: ["src/**", "test/**", "tsdown.config.ts"],
      rules: {
        ...disabledReactDoctorRules,
        ...legacyCompatibilityRules,
      },
    },
  ],
};
